version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - local

networks:
  local:
    name: 'local'
    external: true
